name: Hello World 1

on:
  push:
    paths:
      - '!README.md'
      - '!docs/**'
      - '**.js'
    branches:
      - 'main'
      - 'relase/**'
      - '!dev/**'
  pull_request:
    type: [opened,reopened,synchronize,labeled,unlabeled]
  workflow_dispatch:
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
       - uses: mheap/github-action-required-labels@v5
         with:
            mode: exactly
            count: 0
            labels: "do not build"
       - run: echo "TODAY=$(date +%y-%m-%d)" >> $GITHUB_ENV
       - run: echo Hello World,to day is $TODAY