name: Hello World

on:
  push:
    paths:
      - '!README.md'
      - '!docs/**'
      - '**.js'
    branches:
      - 'main'
      - 'relase/**'
      - '!dev/**'
    workflow_dispatch:
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
       - run: echo "TODAY=$(date +%y-%m-%d)" >> $GITHUB_ENV
       - run: echo Hello World,to day is $TODAY